CREATE TABLE public.tb_categories (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_order_items (
    price double precision,
    quantity integer,
    product_id bigint NOT NULL,
    order_id bigint NOT NULL
);


--
-- Name: tb_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_orders (
    id bigint NOT NULL,
    moment timestamp(6) with time zone,
    order_status integer,
    client_id bigint
);


--
-- Name: tb_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_payments (
    moment timestamp(6) with time zone,
    order_id bigint NOT NULL
);


--
-- Name: tb_product_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_product_category (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: tb_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_products (
    id bigint NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255),
    price double precision
);


--
-- Name: tb_products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_users (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


--
-- Name: tb_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_categories tb_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_categories
    ADD CONSTRAINT tb_categories_pkey PRIMARY KEY (id);


--
-- Name: tb_order_items tb_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_items
    ADD CONSTRAINT tb_order_items_pkey PRIMARY KEY (order_id, product_id);


--
-- Name: tb_orders tb_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_orders
    ADD CONSTRAINT tb_orders_pkey PRIMARY KEY (id);


--
-- Name: tb_payments tb_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payments
    ADD CONSTRAINT tb_payments_pkey PRIMARY KEY (order_id);


--
-- Name: tb_product_category tb_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT tb_product_category_pkey PRIMARY KEY (product_id, category_id);


--
-- Name: tb_products tb_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_products
    ADD CONSTRAINT tb_products_pkey PRIMARY KEY (id);


--
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (id);


--
-- Name: tb_payments fk59gb66nuu5bq1hjeg2og3fi45; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_payments
    ADD CONSTRAINT fk59gb66nuu5bq1hjeg2og3fi45 FOREIGN KEY (order_id) REFERENCES public.tb_orders(id);


--
-- Name: tb_product_category fkeaxc016dqii836yl4ue7ev8j5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT fkeaxc016dqii836yl4ue7ev8j5 FOREIGN KEY (category_id) REFERENCES public.tb_categories(id);


--
-- Name: tb_orders fkjbtk96a5pyaj3qx3bmgvghksg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_orders
    ADD CONSTRAINT fkjbtk96a5pyaj3qx3bmgvghksg FOREIGN KEY (client_id) REFERENCES public.tb_users(id);


--
-- Name: tb_product_category fkq8plupmr9wr1q1vy31m9b0v90; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_product_category
    ADD CONSTRAINT fkq8plupmr9wr1q1vy31m9b0v90 FOREIGN KEY (product_id) REFERENCES public.tb_products(id);


--
-- Name: tb_order_items fkr9uuphipacrs0n0qi7vyxba4q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_items
    ADD CONSTRAINT fkr9uuphipacrs0n0qi7vyxba4q FOREIGN KEY (order_id) REFERENCES public.tb_orders(id);


--
-- Name: tb_order_items fksfeg5hsfxv6v5vlcham57bibu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_order_items
    ADD CONSTRAINT fksfeg5hsfxv6v5vlcham57bibu FOREIGN KEY (product_id) REFERENCES public.tb_products(id);


--
-- PostgreSQL database dump complete
--

\unrestrict UjoA1zUOfxGqg0qTeqt56KJ1SJtUSElTO7kqVD3D2I3jexBC31QPa2hB6aQFncB

